"""Add case_submission column to users

Revision ID: 602be3da853f
Revises: 
Create Date: 2025-07-02 23:27:15.525609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602be3da853f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_submission', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('case_submission')

    # ### end Alembic commands ###
